sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
script:
  - npm run lint
  - npm run flow
  - npm run test:cover
after_success:
  - npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/185b58018ed2c79a58c2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
